/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rocket.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    Circle: THREE.Mesh
    Circle001: THREE.Mesh
  }
  materials: {
    SpaceShipBody: THREE.MeshStandardMaterial
    Bonnet: THREE.MeshStandardMaterial
    SpaceShipOrange: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/rocket.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.83, 0.84, 3.46]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.SpaceShipBody} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Bonnet} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.SpaceShipOrange} />
        <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[0, 0.18, -1]} rotation={[Math.PI / 2, -0.38, 0]} scale={0.12} />
        <mesh geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[0.52, 0.15, -1]} rotation={[Math.PI / 2, -0.38, 0]} scale={0.09} />
      </group>
    </group>
  )
}

useGLTF.preload('/rocket.glb')
